all: 02_conc.c 01b_assert.c 05_struct.c 03_count.c 01_create.c 04_lock.c 06c_return.c 06_return.c
	gcc -O0 -o 02_conc 02_conc.c -pthread
	gcc -O0 -o 01b_assert 01b_assert.c -pthread
	gcc -O0 -o 05_struct 05_struct.c -pthread
	gcc -O0 -g -o 03_count 03_count.c -pthread
	gcc -O0 -g -o 01_create 01_create.c -pthread
	gcc -O0 -o 04_lock 04_lock.c -pthread
	gcc -O0 -o 06c_return 06c_return.c -pthread
	gcc -O0 -o 06_return 06_return.c -pthread